title: 'V6'
output: output/v6/greedy # 输出目录
episodes: 3000 # 运行轮数
track: 120 # 是否捕获行为树运行数据
policy:
    blue: scripts/v6/policy/greedy.xml # 蓝方行为树
options:
#     render: false # 是否渲染
    red_agents: ['red'] # 红方agents
    blue_agents: ['blue'] # 蓝方agents
    indestructible: false # 是否开启无敌模式
    collision_scale: 1 # 碰撞倍数，越大越容易发生碰撞
    aircraft_missile_count: 1000 # 导弹数量认为是无限多
    aircraft_fuel_capacity: 180000 # 飞机油量认为无限多
    aircraft_fire_missile_interval: 15 # 发射导弹时间间隔15s
#     aircraft_radar_radius: 10000
    device: cpu
context: # 行为树环境变量，可以在行为树中通过{{}}来传递
    rl_algo: PPO # 强化学习算法
    models_dir: '' # 从哪个模型里加载
    models_episode: 0

