context:
    batch_size: 32
    features_dim: 128
    learning_starts: 128
episodes: 3000
options:
    aircraft_fire_missile_interval: 15
    aircraft_fuel_capacity: 180000
    aircraft_missile_count: 3
    blue_agents:
    - blue_1
    collision_scale: 1
    device: auto
    indestructible: false
    max_duration: 1800
    red_agents:
    - red_1
    render: true
    title: scripts/v7-base
output: scripts/v7/base
policy:
    blue: scripts/v7/policy/greedy.xml
    red: manual.xml
title: scripts/v7-base
track: -1
