title: '{{filedir}}-{{filename}}'
output: '{{filedir}}/{{filename}}' # 输出目录
episodes: 3000 # 运行轮数
track: -1 # 是否捕获行为树运行数据
policy:
    blue: '{{filedir}}/policy/greedy.xml' # 蓝方行为树
    red: 'manual.xml'
#     blue: 'manual.xml' # 蓝方行为树
options:
#     render: false # 是否渲染
    red_agents: ['red_1'] # 红方agents
    blue_agents: ['blue_1'] # 蓝方agents
    indestructible: false # 是否开启无敌模式
    collision_scale: 1 # 碰撞倍数，越大越容易发生碰撞
    aircraft_missile_count: 3 # 每个飞机上安装3枚导弹
    aircraft_fuel_capacity: 180000 # 飞机油量认为无限多
    aircraft_fire_missile_interval: 15 # 发射导弹时间间隔15s
    max_duration: 1800 # 一局对战最多1800秒
#     aircraft_radar_radius: 10000
    device: auto
context: # 行为树环境变量，可以在行为树中通过{{}}来传递
#     models_dir: 'output/v6/ppo-greedy/models'
    features_dim: 128
    learning_starts: 128
    batch_size: 32
